# CONSTANTES
STATUS_OK = 0
FILE_TOO_BIG = 1
CHUNK_SIZE = 256
HEADER_SIZE = 2
PACKAGE_SIZE = 1
ACK_SIZE = 1
CLIENT_METHOD_SIZE = 1
LENGTH_BYTES = 8
STATUS_CODE_SIZE = 1
TIMEOUT = 5 # RANDOM, PERO PONER ALGUNA JUSTIFICACION EN EL INFORME
MAX_TIMEOUTS = 3

UPLOAD = 0
DOWNLOAD = 1